//ruoli che si hanno a disposizione

module.exports = {
    read:['Admin', 'Professore','Studente'],
    write:['Admin', 'Professore'],
    writeAdmin:['Admin']
    
    /*operations:[
        {op:"/AddCertificationToCertificationSession",array: ["Admin"]},
        {op:"/AddCourseToModule",array: ["Admin"]},
        {op:"/AddModuleToStudyPlan",array: ["Admin"]},
        {op:"/Address",array: ["Admin"]},
        {op:"/AddStudentModuleToSemester",array: ["Admin"]},
        {op:"/AddStudentToStudentModule",array: ["Admin"]},
        {op:"/Certification",array: ["Admin"]},
        {op:"/CertificationSession",array: ["Admin"]},
        {op:"/Collaborator",array: ["Admin"]},
        {op:"/Course",array: ["Admin"]},
        {op:"/CreateCertification",array: ["Admin"]},
        {op:"/CreateCertificationSession",array: ["Admin"]},
        {op:"/CreateCourse",array: ["Admin"]},
        {op:"/CreateDepartment",array: ["Admin"]},
        {op:"/CreateModule",array: ["Admin"]},
        {op:"/CreateSemester",array: ["Admin"]},
        //{op:"/CreateStudent",array: ["Admin"]},
        {op:"/CreateStudentModule",array: ["Admin"]},
        {op:"/CreateStudyPlan",array: ["Admin"]},
        {op:"/DeleteCertification",array: ["Admin"]},
        {op:"/DeleteCertificationSession",array: ["Admin"]},
        {op:"/DeleteCourse",array: ["Admin"]},
        {op:"/DeleteDepartment",array: ["Admin"]},
        {op:"/DeleteModule",array: ["Admin"]},
        {op:"/DeleteSemester",array:["Admin"]},
        {op:"/DeleteStudent",array: ["Admin"]},
        {op:"/DeleteStudentModule",array: ["Admin"]},
        {op:"/DeleteStudyPlan",array: ["Admin"]},
        {op:"/Department",array: ["Admin"]},
        {op:"/Module",array: ["Admin"]},
        {op:"/Query",array: ["Admin"]},
        {op:"/RemoveCertificationFromCertificationSession",array: ["Admin"]},
        {op:"/RemoveCourseFromModule",array: ["Admin"]},
        {op:"/RemoveModuleFromStudyPlan",array: ["Admin"]},
        {op:"/RemoveStudentFromStudentModule",array: ["Admin"]},
        {op:"/RemoveStudentModuleFromSemester",array: ["Admin"]},
        {op:"/Semester",array: ["Admin"]},
        {op:"/Student",array: ["Admin"]},
        {op:"/StudentModule",array: ["Admin"]},
        {op:"/StudyPlan",array: ["Admin"]},
        {op:"/SubscriptionToSemester",array: ["Admin"]},
        {op:"/System",array: ["Admin"]},
        {op:"/UpdateCertification",array: ["Admin"]},
        {op:"/UpdateCertificationSession",array: ["Admin"]},
        {op:"/UpdateCourse",array: ["Admin"]},
        {op:"/UpdateDepartment",array: ["Admin"]},
        {op:"/UpdateModule",array: ["Admin"]},
        {op:"/UpdateSemester",array: ["Admin"]},
        {op:"/UpdateStudent",array: ["Admin"]},
        {op:"/UpdateStudentModule",array: ["Admin"]},
        {op:"/UpdateStudyPlan",array: ["Admin"]},
        {op:"/register",array:["Admin"]},
        {op:"/login",array:["Admin"]},
        {op:"/users",array:["Admin"]},
        {op:"/users/delete/[a-zA-Z@.]+",array:["Admin"]},
        {op:'/queries/selectStudentByName?[a-zA-Z]+',array:["Admin"]},
        {op:'/queries/selectStudentsBySurname?[a-zA-Z]+',array:["Admin"]},
        {op:'/queries/selectStudentsBySerialNumber?[a-zA-Z]+',array:["Admin"]},
        {op:'/queries/selectDepartmentByName?[a-zA-Z]+',array:["Admin"]},
        {op:'/queries/selectCoursesByName?[a-zA-Z]+',array:["Admin"]},
        {op:'/queries/selectCoursesByCourseCode?[a-zA-Z]+',array:["Admin"]},
        {op:'/queries/selectModulesByName?[a-zA-Z]+',array:["Admin"]},
        {op:'/queries/selectModulesByModuleCode?[a-zA-Z]+',array:["Admin"]},
        {op:'/queries/selectStudyPlanByName?[a-zA-Z]+',array:["Admin"]},
        {op:'/queries/selectStudyPlanByModuleCode?[a-zA-Z]+',array:["Admin"]},
        {op:'/queries/selectSemestersByName?[a-zA-Z]+',array:["Admin"]},
        {op:'/queries/selectSemestersByModuleCode?[a-zA-Z]+',array:["Admin"]},
        {op:'/queries/selectCertificationByStudentName?[a-zA-Z]+',array:["Admin"]},
        {op:'/queries/selectCertificationByStudentSurame?[a-zA-Z]+',array:["Admin"]},
        {op:'/queries/selectCertificationByModuleCode?[a-zA-Z]+',array:["Admin"]},
        {op:'/[a-zA-Z]+',array:["Admin"]},
        {op:'/CertificationPerStudent/[0-9a-zA-Z]+',array:["Admin"]},
        {op:'/[a-zA-Z]+/[0-9a-zA-Z]+',array:["Admin"]},  
        {op:'/[a-zA-Z]+',array:["Admin"]},    
        {op:'/[a-zA-Z0-9]+/Upload',array:["Admin"]},    
        {op:'/[a-zA-Z0-9]+/Download/[a-zA-Z0-9 -]+\.[a-zA-Z]+',array:["Admin"]},
        {op:'/[a-zA-Z0-9]+/Delete/[a-zA-Z0-9\s\W]+\.[a-zA-Z]+',array:["Admin"]}
    ]*/
}